name: Build and deploy documentation (test)
on:
  push
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python3 -m pip install sphinx==6.2.1 sphinx_rtd_theme sphinx-copybutton myst_parser nbsphinx setuptools
          python3 -m pip install poetry
      - name: poetry create requirements file
        run: |
          poetry --version
          poetry update
          poetry export -f requirements.txt --output requirements.txt
      - name: install package using pip
        run: |
          python3 -m pip install -r requirements.txt
      - name: Sphinx build
        run: |
          sphinx-build -a -E docs _build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true